
[[_introduction]]
= Introduction

The plugin converts your Groovy code to javascript, allowing to use your Groovy code in your gsp files.

If you want to convert groovy files to javascript, use groovy templates on the client side, generate
require.js modules from your groovy code. Don't forget to use https://github.com/chiquitinxx/grooscript-gradle-plugin[gradle plugin].
You can use both plugins in your grails 3 project.

So, your *groovy code will run in your browser*!

== Important

If you have any ideas on how to

- improve this plugin,
- use grooscript phantomjs support,
- statically compile your templates,
- or improve domain classes options,
- or anything else...

don't hesitate to *open an issue or improvement* on https://github.com/chiquitinxx/grooscript-grails3-plugin/issues[Github]
or email me at grooscript@gmail.com.

I have created this documentation with http://asciidoctor.org/[asciidoctor]!

== Requisites

This plugin works with Grails 3. You also need assets pipeline and the cache plugin.

- Use _<asset:deferredScripts/>_ in your gsp files with grooscript tags.
- You have to import *grosscript-grails.js* when you use grooscript tags.
- The plugin uses __jquery__, so remember to add that dependency.
- Domain classes support is still experimental, *don't use it in production code*, as explained <<_use_in_production,here>>.

To use the plugin just add it to your grails 3 dependencies in your +build.gradle+:

[source,groovy]
[subs="verbatim,attributes"]
--
dependencies {
    ...
    compile "org.grails.plugins:grooscript:{plugin-version}"
    ...
}
--

== What is new in {plugin-version}

- Fix remote domain classes in windows

== What is new in 1.1.3, 1.1.2 and 1.1.1

- Upgraded to grooscript 1.2.2
- Now you can set the websockets endpoint
- Fixes

== What is new in 1.1.0

- Generation of remote domain classes code for production.
- Use grooscript version 1.2.0

== Changes version 1.0.0

- Stable release 1.0.0 to work with grails 3.
- Use grooscript version 1.1.1

