[[_localDomain]]
== <grooscript:model>

With this tag you can use your domain classes in the browser / client. The difference between this tag and
remoteModel is, no sync between server and client with this tag. So, you can use the domain class in the client,
but nothing will be added, updated or deleted in the server. Just for create a little database in the client and /
or use domain classes and methods in the client. This is good, for example, for don't repeat code between server and
client. Also you can validate your domain classes in the client.

*This tag is still experimental, don't use in production.*

[source,groovy]
--
package rest

import grails.rest.Resource

@Resource(uri='/books')
class Book {

    String title
    String author

    static constraints = {
        author nullable: true
    }
}
--

Activate use in your gsp's with:

[source,html]
--
<grooscript:remoteModel domainClass="Book"/>
--

In the _domainClass_ you have to put the name of the domain class annotated with _@Resource_. The code of the domain
class is converted to javascript, and you can use properties and methods in the client. If you want to
see in action, please take a look at this link:rest-demo.html[guide].

