[[_templates]]
== <grooscript:template>

You can create html templates using this tag. A template is a piece of groovy code that will be
executed inside a html builder. So you generate javascript code that will run as a DSL(HtmlBuilder). In groovy exists
some html builders, this is a simple one, that is available inside grooscript js libs. For example:

[source,html]
--
<grooscript:template>
    ul {
        5.times { number ->
            li "${number} li item"
        }
    }
</grooscript:template>
--

This tag transform the code in a javascript function that returns html code. The options of this tag are:

onLoad:: by default is true, so the function runs on document ready, and then you html code appears.
functionName:: by default a random name is used. But you can define name of the function and use it.
itemSelector:: jquery selector of the dom object where html code will be injected.
onEvent:: to execute the function when event or events are launched.

You can combine grooscript tags to create dynamic applications in the client side using *groovy*. The variable *data*
is available inside the template tag, that is the param used in the template function call.

[source,html]
--
<div id="list"></div>

<grooscript:template onLoad="false" functionName="refreshList" itemSelector="#list">
    ul {
        data.each { book ->
            li {
                p 'Id: ' + book.id + ' Name: ' + book.title
            }
        }
    }
</grooscript:template>

<grooscript:code>
    $(document).ready {
        refreshList [[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']]
    }
</grooscript:code>
--

== <grooscript:initSpringWebsocket>

Websocket support explained below. With this tag you start websocket connections on the client.

[source,html]
--
<grooscript:initSpringWebsocket/>

<!-- or -->

<grooscript:initSpringWebsocket>
    println 'Connected! Websocket is up!'
</grooscript:initSpringWebsocket>
--

You can put groovy code inside the tag, and that code will run in your browser after websocket connection done.

== <grooscript:onServerEvent>

You can react to websocket events from the server:

[source,html]
--
<grooscript:onServerEvent path="/topic/hello">
    $("#helloDiv").append '<p>'+data+'</p>'
</grooscript:onServerEvent>

<grooscript:onServerEvent path="/topic/books" type="Book">
    data.each { book ->
        $("#helloDiv").append '<p>'+book.coolFormat()+'</p>'
    }
</grooscript:onServerEvent>
--

_type_ is optional parameter with the type name of the _data_ that come from the server.