
With this plugin, you can use spring 4 websockets support. The plugin offer 2 tags for your gsp's, to activate
websockets and for listen websocket messages from the server, also you can send messages to the server. You can use
groovy code to listen and send messages in the client side. In the server side you have to include websocket
support via plugin or spring boot support. Communication is done using SockJs and Stomp.

== Setup

You need grails 3.0+, this plugin and jquery. Add jquery.js to `grails-app/assets/javascripts`. The
http://grails.org/plugin/spring-websocket[websocket plugin] do spring websocket stuff for us, is well
documented and has good https://github.com/zyro23/grails-spring-websocket[support].

First add plugins in your +build.config+:

[source,groovy]
[subs="verbatim,attributes"]
--
dependencies {

    ...
    compile "org.grails.plugins:grails-spring-websocket:2.0.0"
    compile "org.grails.plugins:grooscript:{plugin-version}"
    ...
}
--

== Server side

In the server side you have to use websockets plugin support, for example:

[source,groovy]
--
import org.springframework.messaging.handler.annotation.MessageMapping
import org.springframework.messaging.handler.annotation.SendTo

class ExamplesController {

    @MessageMapping("/hello")
    @SendTo("/topic/hello")
    protected Map hello(String world) {
        def str = "Message received: ${world}"
        return [msg: str.toString()]
    }
}
--

== Client side

There are two tags, first tag init connection and execute any groovy code when connection is up:

[source,html]
--
<!DOCTYPE html>
<html>
<head>
    <asset:javascript src="jquery" />
    <asset:javascript src="grooscript-grails" />
    <asset:javascript src="spring-websocket" />
</head>
<body>

    <grooscript:initSpringWebsocket/>

    <!-- or -->

    <grooscript:initSpringWebsocket withDebug="true"> //You can activate debug in console
        println 'Websocket is up!'
    </grooscript:initSpringWebsocket>

    <asset:deferredScripts/>

</body>
</html>
--

The connection between server and the client uses sockjs and stomp, see
http://grails.org/plugin/spring-websocket[websocket plugin] for more info. In javascript there is a variable called
*websocketClient* with the stomp client object. You can send websocket messages to the server with:

[source,groovy]
--
<grooscript:initSpringWebsocket>
    GrooscriptGrails.sendWebsocketMessage("/app/hello", "world")
</grooscript:initSpringWebsocket>
--

The other tag, is for react to events that come from the server. If you have send an event in the server, then you
can listen that event using groovy:

[source,html]
--
<grooscript:onServerEvent path="/topic/hello">
    $("#helloDiv").append '<p>'+data+'</p>' //<1>
</grooscript:onServerEvent>

<grooscript:onServerEvent path="/topic/books">
    data.each { book ->
        $("#helloDiv").append '<p>'+book.title+'</p>'
    }
</grooscript:onServerEvent>

<asset:deferredScripts/> // <2>
--
<1> *data* is the variable with the 'groovy' object that come from the server.
<2> grooscript plugin uses asset pipeline plugin. Use this tag to process _grooscript_ tags.

And that's all, just use groovy in the server and in the client. Don't have to write javascript code or worry
about browser stuff. Grooscript and spring websocket plugins do the work for you.

Also, you can work with groovy objects in the client side. For example if you send from the server a list of books,
 and that book is a domain class like this:

[source,groovy]
--
class Book {

    String title
    String author

    String coolFormat() {
        "${title.split(' ').collect { it.capitalize() }.join ' '} - ${author.toUpperCase()}"
    }
}
--

Then, in your gsp, if you convert that code to javascript and included in the gsp, you can use groovy object functions:

[source,html]
--
<grooscript:onServerEvent path="/topic/books" type="Book">
    data.each { book ->
        $("#helloDiv").append '<p>'+book.coolFormat()+'</p>'
    }
</grooscript:onServerEvent>
--

== Resume

Is very easy add websocket support to your grails 2.4 application. And now with grooscript plugin, you can create and
listen to websocket events in groovy. Never was so easy add websockets with groovy to your grails applications.

You can combine websocket support with other grooscript tags to create dynamic applications in the client side.