
[[_helpers]]
= Grails helpers

Grooscript and this plugin offer some helpers to work with html, javascript or grails from your groovy code.

You can use the `GrooscriptGrails` class from your groovy code, in grooscript tags or groovy code. The code will run only in your browser (client side), no server calls will be made.

[source,groovy]
--
package org.grooscript.grails.util

class GrooscriptGrails {
    static findComponentById(String id) //<1>
    static void doRemoteCall(String controller, String action, Map params, Closure onSuccess, Closure onFailure) //<2>
    static void sendWebsocketMessage(String channel, message) //<3>
    static void notifyEvent(String eventName, data) //<4>
}
--
<1> Finf a component by id
<2> Do a remote ajax call
<3> Send a message to server via websockets
<4> Send a grails event

Example (calls `addBook` on controller `books`):

[source,groovy]
--
<grooscript:code>
	GrooscriptGrails.doRemoteCall('books', 'addBook', [title: 'A title'],
                                      { println 'All was Ok' }, 
                                      { println 'Error adding book' })
</grooscript:code>
--

