
[[_introduction]]
= Introduction

The plugin converts your Groovy code to javascript, allowing to use your Groovy code in your gsp files.

If you want to convert groovy files to javascript, use groovy templates on the client side, generate
require.js modules from your groovy code. Don't forget to use https://github.com/chiquitinxx/grooscript-plugins/tree/master/gradle-plugin[gradle plugin].
You can use both plugins in your grails 3 project, and you must use both if you use grooscript:component tag.

So, your *groovy code will run in your browser*!

== Important

If you have any ideas on how to

- improve this plugin,
- statically compile your templates,
- or improve component options,
- or anything else...

don't hesitate to *open an issue or improvement* on https://github.com/chiquitinxx/grooscript-plugins[Github]
or email me at grooscript@gmail.com.

I have created this documentation with http://asciidoctor.org/[asciidoctor]!

== Requisites

This plugin works with Grails 3. It also need assets pipeline and the cache plugin.

- Use _<asset:deferredScripts/>_ in your gsp files with grooscript tags.
- You don't have to import *grosscript-grails.js* when you use grooscript tags, plugin does for you.
- The plugin *don't* need __jquery__, but you can work with it.

To use the plugin just add it to your grails 3 dependencies in your +build.gradle+:

[source,groovy]
[subs="verbatim,attributes"]
--
dependencies {
    ...
    compile "org.grails.plugins:grooscript:{plugin-version}"
    ...
}
--

== What is new in {plugin-version}

- Use grails events between server and client using websockets.
- No need to add grooscript libs in your gsp's.
- Removed jquery as dependency.
- Removes grooscript:remoteDomain feature.
- Improve file generation of components for the jar / war, no need execute a task, gradle plugin does it automatically.
- Add more tests.

== What is new in 1.2.x

- New tag for reload pages in development

== What is new in 1.2

- Use groovy classes as web components in your gsp's

== What is new in 1.1.x

- Generation of remote domain classes code for production
- Set the websockets endpoint name
- Upgrade grooscript version
- Fixes

== Changes version 1.0.0

- Stable release 1.0.0 to work with grails 3.
- Use grooscript version 1.1.1

