[[_templates]]
== <grooscript:template>

You can create html templates using this tag. A template is a piece of groovy code that will be
executed inside a html builder. So you generate javascript code that will run as a DSL(HtmlBuilder). In groovy exists
some html builders, this is a simple one, that is available inside grooscript js libs. For example:

[source,html]
--
<grooscript:template>
    ul {
        5.times { number ->
            li "${number} li item"
        }
    }
</grooscript:template>
--

This tag transform the code in a javascript function that returns html code. The options of this tag are:

onLoad:: by default is true, so the function runs on document ready, and then you html code appears.
functionName:: by default a random name is used. But you can define name of the function and use it.
itemSelector:: jquery selector of the dom object where html code will be injected.

You can combine grooscript tags to create dynamic applications in the client side using *groovy*. The variable *data*
is available inside the template tag, that is the param used in the template function call.

[source,html]
--
<div id="list"></div>

<grooscript:template onLoad="false" functionName="refreshList" itemSelector="#list">
    ul {
        data.each { book ->
            li {
                p 'Id: ' + book.id + ' Name: ' + book.title
            }
        }
    }
</grooscript:template>

<grooscript:code>
    $(document).ready {
        refreshList([[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']])
    }
</grooscript:code>
--
