For more about grails websocket plugin, please visit https://github.com/zyro23/grails-spring-websocket[https://github.com/zyro23/grails-spring-websocket]

After install the plugin, then you can work with websockets in your grails application without configuration.

== Server side

In the server side you have to use websockets support, for example:

[source,groovy]
--
import org.springframework.messaging.handler.annotation.MessageMapping
import org.springframework.messaging.handler.annotation.SendTo

class ExamplesController {

    @MessageMapping("/hello")
    @SendTo("/topic/hello")
    protected Map hello(String world) {
        def str = "Message received: ${world}"
        return [msg: str.toString()]
    }
}
--

== Client side

There are two tags, first tag init connection and execute any groovy code when connection is up:

[source,html]
--
<!DOCTYPE html>
<html>
<head>
    <asset:javascript src="jquery" />
    <asset:javascript src="grooscript-grails" />
    <asset:javascript src="spring-websocket" />
</head>
<body>

    <grooscript:initSpringWebsocket/>

    <!-- or -->

    <grooscript:initSpringWebsocket withDebug="true"> //You can activate debug in console
        println 'Websocket is up!'
    </grooscript:initSpringWebsocket>

    <asset:deferredScripts/>

</body>
</html>
--

The connection between server and the client uses sockjs and stomp, see
https://github.com/zyro23/grails-spring-websocket[websocket plugin] for more info. In javascript there is a variable called
*websocketClient* with the stomp client object. You can send websocket messages to the server with:

[source,groovy]
--
<grooscript:initSpringWebsocket>
    GrooscriptGrails.sendWebsocketMessage("/app/hello", "world")
</grooscript:initSpringWebsocket>
--

The other tag, is for react to events that come from the server. If you have send an event in the server, then you
can listen that event using groovy:

[source,html]
--
<grooscript:onServerEvent path="/topic/hello">
    $("#helloDiv").append '<p>'+data+'</p>' //<1>
</grooscript:onServerEvent>

<grooscript:onServerEvent path="/topic/books">
    data.each { book ->
        $("#helloDiv").append '<p>'+book.title+'</p>'
    }
</grooscript:onServerEvent>

<asset:deferredScripts/> // <2>
--
<1> *data* is the variable with the 'groovy' object that come from the server.
<2> grooscript plugin uses asset pipeline plugin. Use this tag to process _grooscript_ tags.

And that's all, just use groovy in the server and in the client. Don't have to write javascript code or worry
about browser stuff. Grooscript and spring websocket plugins do the work for you.

Also, you can work with groovy objects in the client side. For example if you send from the server a list of books,
 and that book is a domain class like this:

[source,groovy]
--
class Book {

    String title
    String author

    String coolFormat() {
        "${title.split(' ').collect { it.capitalize() }.join ' '} - ${author.toUpperCase()}"
    }
}
--

Then, in your gsp, if you convert that code to javascript and included in the gsp, you can use groovy object functions:

[source,html]
--
<grooscript:onServerEvent path="/topic/books" type="Book">
    data.each { book ->
        $("#helloDiv").append '<p>'+book.coolFormat()+'</p>'
    }
</grooscript:onServerEvent>
--